In [1]:
import torch
import numpy as np

## 1. Тензоры в pytorch

In [6]:
a = torch.tensor([1,2,3.0,4,5], dtype=torch.float32)
b = torch.arange(5, 10, dtype=torch.float32)
c = torch.ones(5, 4, dtype=torch.float32)
a, b, c

(tensor([1., 2., 3., 4., 5.]),
 tensor([5., 6., 7., 8., 9.]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [38]:
a.dtype

torch.float32

Над тензорами в pytorch можно производить все матиматические операции как в numpy

In [65]:
operation_names = ['a','b', 'a * b', 'a + b', 'a - b', 'a / b', 'a//b', 'a**b', 'a > b', 'a==b']
operations = [a, b, a * b, a + b, a - b, a / b, a//b, a**b, a > b, a==b]
for name, result in zip(operation_names, operations):
    print(name, result, sep='\t')

a	tensor([1., 2., 3., 4., 5.])
b	tensor([5., 6., 7., 8., 9.])
a * b	tensor([ 5., 12., 21., 32., 45.])
a + b	tensor([ 6.,  8., 10., 12., 14.])
a - b	tensor([-4., -4., -4., -4., -4.])
a / b	tensor([0.2000, 0.3333, 0.4286, 0.5000, 0.5556])
a//b	tensor([0., 0., 0., 0., 0.])
a**b	tensor([1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04, 1.9531e+06])
a > b	tensor([False, False, False, False, False])
a==b	tensor([False, False, False, False, False])


Можно работать и с обычными числами, например так, используя специализированные функции pytorch для сложения, умножения и т.д.:

In [47]:
x = 1.
y = 2.
torch.add(x, y), torch.mul(x,y), torch.sub(x,y)

(tensor(3., dtype=torch.float64),
 tensor(2., dtype=torch.float64),
 tensor(-1., dtype=torch.float64))

Однако для простоты записи, удобнее сразу перевести все переменные в pytorch тензоры:

In [61]:
x = torch.tensor(1.)
y = torch.tensor(2.)
torch.add(x, y), torch.mul(x,y), torch.sub(x,y)

(tensor(3.), tensor(2.), tensor(-1.))

тогда вместо pytorch методов можно пользоваться переопределёнными обычными математическими операциями:

In [62]:
x + y, x * y, x - y

(tensor(3.), tensor(2.), tensor(-1.))

## 2. Автоматическое дифференцирование

In [45]:
x = torch.tensor(15., requires_grad=True)
y = torch.tensor(24.)

f = torch.log(x**2 + y**2)

In [46]:
f

tensor(6.6859, grad_fn=<LogBackward>)

In [25]:
u = torch.exp(f)
u

tensor(801.0001, grad_fn=<ExpBackward>)

In [26]:
f.backward()

In [27]:
x

tensor(15., requires_grad=True)

In [28]:
x.grad

tensor(0.0375)

In [29]:
y

tensor(24.)

In [30]:
print(y.grad)

None


### Более сложный пример

In [31]:
W = torch.rand(3, 4)
x = torch.arange(4, dtype=torch.float32)
W, x

(tensor([[0.3523, 0.1122, 0.9174, 0.3730],
         [0.2062, 0.9226, 0.3375, 0.1069],
         [0.0943, 0.8741, 0.1801, 0.0188]]), tensor([0., 1., 2., 3.]))

In [32]:
W.requires_grad_(True)

tensor([[0.3523, 0.1122, 0.9174, 0.3730],
        [0.2062, 0.9226, 0.3375, 0.1069],
        [0.0943, 0.8741, 0.1801, 0.0188]], requires_grad=True)

In [33]:
z = W.dot(x)

RuntimeError: 1D tensors expected, but got 2D and 1D tensors

Unlike NumPy’s dot, torch.dot intentionally only supports computing the dot product of two 1D tensors with the same number of elements.

In [34]:
z = W.matmul(x)
y = torch.relu(z)
target = torch.tensor([1., 1.2, 1.4])
loss = torch.sum((y - target)**2)

In [35]:
loss

tensor(4.7970, grad_fn=<SumBackward0>)

In [36]:
loss.backward()

In [37]:
W.grad

tensor([[ 0.0000,  4.1324,  8.2648, 12.3972],
        [ 0.0000,  1.4365,  2.8731,  4.3096],
        [-0.0000, -0.2185, -0.4369, -0.6554]])

In [38]:
x.grad